name: Release NPM package

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.0.21"
      - name: Install Dependencies
        run: bun install
      - name: Release
        run: bun release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
